return require('packer').startup(function(use)
  -- allow packer (the plugin manager) to manage itself
  use 'wbthomason/packer.nvim'

  use 'ellisonleao/gruvbox.nvim'
  use 'itchyny/lightline.vim'
  use 'nvim-lua/popup.nvim'
  use 'nvim-lua/plenary.nvim'
  use 'nvim-telescope/telescope.nvim'
  use 'nvim-telescope/telescope-fzy-native.nvim'
  use 'prettier/vim-prettier'
  use 'tpope/vim-surround'
  use 'tpope/vim-commentary'
  use 'christoomey/vim-system-copy'
  use 'mattn/emmet-vim'
  use 'neovim/nvim-lspconfig'
  use 'kyazdani42/nvim-web-devicons'
  use 'nvim-treesitter/nvim-treesitter'
  use 'hrsh7th/cmp-nvim-lua'
  use 'hrsh7th/cmp-nvim-lsp'
  use 'hrsh7th/cmp-buffer'
  use 'hrsh7th/cmp-path'
  use 'hrsh7th/cmp-cmdline'
  use 'hrsh7th/nvim-cmp'
  use 'L3MON4D3/LuaSnip'
  use 'saadparwaiz1/cmp_luasnip'
end)
