#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc wm -O DP-2 DP-4

bspc monitor 'DP-4' -d 6 7 8 9
bspc monitor 'DP-2' -d 1 2 3 4 5

bspc config border_width 2
bspc config window_gap 12 
bspc config border_radius 5
bspc config split_ratio 0.50
bspc config borderless_monocle false
bspc config gapless_monocle false
bspc config click_to_focus true
bspc config apply_floating_atom true
bspc config history_aware_focus true

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc rule -a Screenkey manage=off

eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh) export SSH_AUTH_SOCK

# mouse pointer
xsetroot -cursor_name left_ptr &

# polybar
$HOME/.config/polybar/launch.sh &

connected_display=$(xrandr --query |awk '/\<connected\>/{print $1}')

if [ $connected_display = "eDP1" ]; then
  $HOME/.config/polybar/laptop_launch.sh &
else
  $HOME/.config/polybar/desktop_launch.sh &
fi

# touchpad
# hides mouse when you are not using it
unclutter &

xinput set-prop "SYNA2393:00 06CB:7A13 Touchpad" "libinput Natural Scrolling Enabled" 1
xinput set-prop "SYNA2393:00 06CB:7A13 Touchpad" "libinput Click Method Enabled" 0 1
xinput set-prop "SYNA2393:00 06CB:7A13 Touchpad" "libinput Tapping Enabled" 1
xinput set-prop "SYNA2393:00 06CB:7A13 Touchpad" "libinput Disable While Typing Enabled" 1
xinput set-prop "SYNA2393:00 06CB:7A13 Touchpad" "libinput Accel Profile Enabled" 1, 0
